### ISSUE TITLE
Option '__action__' is not valid in section 'filament_switch_sensor filament_sensor_2' after update

### ISSUE THREAD

**Issue by TrainAss** [pellcorp/creality#157]
After completing an update, the following Klipper error is presented

> Option '__action__' is not valid in section 'filament_switch_sensor filament_sensor_2'
> 
> Once the underlying issue is corrected, use the "RESTART"
> command to reload the config and restart the host software.
> Printer is halted

This is due to this section in printer.cfg

![image](https://github.com/user-attachments/assets/227539ca-7199-4aa8-b638-f5dbfa570a9f)

By default, most people don't have anything connected to the filament sensor 2 port on their toolhead. I always have to re-comment this section out after every update. Can we have it commented out by default for the next update?

**Comment by pellcorp** [comment]
this is a bug, it is due to config overrides, will investigate why its doing that, can you post all the files from `/usr/data/pellcorp-backups` and `/usr/data/pellcorp-overrides` please.

**Comment by pellcorp** [comment]
So you want to remove the filament_sensor_switch filament_sensor_2 section?   So I did this which results in the following /usr/data/pellcorp-overrides/printer.cfg

```
[filament_switch_sensor filament_sensor_2]
__action__: DELETED
```

I am guessing there is something wrong with config-helper.py for this, so I will investigate and see if I can fix, for now though because it does not really matter to leave that enabled, just remove the 'action' field and leave the `filament_sensor_2` enabled while I work on a fix.

**Comment by pellcorp** [comment]
Ok, so I don't need those files, its a bug in config-helper.py, it is ignoring any section deletes unless they are includes, but config-overrides.py is generating section deletes for printer.cfg, so I will get them into line.

**Comment by pellcorp** [comment]
this has been fixed
